name: integration-tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release**

jobs:
  GrAITorchTests:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup Conda Environment
        run: |
          conda create --name graitorch-ci python=3.9
          conda env list

      - name: Install Python Library
        working-directory: Tests/GrAITorchTests/Base
        run: |
          conda activate graitorch-ci
          pip="$(dirname `which python`)"/pip
          $pip install -e .
          
      - name: Test
        run: |
          conda activate graitorch-ci
          swift test --filter GrAITorchTests
      
      - name: Remove Conda Environment
        if: always()
        run: conda env remove --name graitorch-ci
