name: Swift

on: [push]

jobs:
  MAKit:
    runs-on: self-hosted

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
        
  MAData:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
