name: Swift

on: [push]

jobs:
  MAKit:
    runs-on: self-hosted

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
        
  MAData:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: ~/opt/anaconda3
        with:
          activate-environment: makit-ci
          python-version: 3.7
          auto-activate-base: false
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
