name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          swift-version: "5.6.0"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
