name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main
      - release**

jobs:
  GrAITests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Test
        run: |
            swift test -c release \
                --filter GrAITests \
                --parallel \
                --enable-test-discovery | \
                xcpretty --test --color
