name: unit-tests

on: [push]

jobs:
  GrAITests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test -c release --filter GrAITests
