name: unit-tests

on: [push]

jobs:
  MAKitTests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test --filter MAKitTests
